version: '3.8'

services:
  fastq_processor:
    image: quay.io/biocontainers/fastp:0.23.4--h5f740d0_0
    volumes:
      - ./data:/data
      - ./results:/results

  aligner:
    image: quay.io/biocontainers/bwa:0.7.17--hed695b0_7
    volumes:
      - ./data:/data
      - ./results:/results

  sam_processor:
    image: quay.io/biocontainers/samtools:1.17--h00cdaf9_0
    volumes:
      - ./data:/data
      - ./results:/results

  hic_processor:
    build:
      context: .
      dockerfile: Dockerfile.hicpro
    volumes:
      - ./data:/data
      - ./results:/results
    environment:
      - CONDA_PREFIX=/opt/conda/envs/hicpro_env
      
  peak_caller:
    image: quay.io/biocontainers/macs2:2.2.9.1--py310h1425a21_0
    volumes:
      - ./data:/data
      - ./results:/results

  annotator:
    image: quay.io/biocontainers/bedtools:2.30.0--h7d7f7ad_2
    volumes:
      - ./data:/data
      - ./results:/results

  ml_environment:
    build:
      context: .
      dockerfile: Dockerfile.ml
    volumes:
      - ./data:/data
      - ./results:/results
      - ./scripts:/scripts
    ports:
      - "8888:8888"
    environment:
      - NODE_VERSION=20

  visualizer:
    image: quay.io/biocontainers/pygenometracks:3.7--pyhdfd78af_0
    volumes:
      - ./data:/data
      - ./results:/results
