name: hicpro_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - pysam
  - bx-python
  - iced
  - cooler
  - pandas
  - h5py
  - bowtie2
  - samtools
  - r-base
  - r-ggplot2
  - r-rcolorbrewer
